name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      ZIG_VERSION: 0.13.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Check Zig version
        run: zig version

      - name: Create bin/ directory
        run: mkdir bin

      - name: Build Windows X86_64
        run: |
          zig cc writeLicense.c main.c -target x86_64-windows-gnu -O2 -o bin/windows_x86_64.exe
          rm -rf bin/windows_x86_64.pdb

      - name: Build Windows ARM64
        run: |
          zig cc writeLicense.c main.c -target aarch64-windows-gnu -O2 -o bin/windows_arm64.exe
          rm -rf bin/windows_arm64.pdb

      - name: Build MacOS ARM64
        run: zig cc writeLicense.c main.c -target aarch64-macos -O2 -o bin/macos_arm64

      - name: Build MacOS X86_64
        run: zig cc writeLicense.c main.c -target x86_64-macos -O2 -o bin/macos_x86_64

      - name: Build Linux ARM64
        run: zig cc writeLicense.c main.c -target aarch64-linux-gnu -O2 -o bin/linux_arm64

      - name: Build Linux X86_64
        run: zig cc writeLicense.c main.c -target x86_64-linux-gnu -O2 -o bin/linux_x86_64

      - name: Push changes
        run: |
          git config --global user.name "Dark Actions"
          git config --global user.email "dark-actions@doitall.work"
          git add .
          git commit -m "Add binaries"
          git push origin master
