name: Build project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZIG_VERSION: 0.13.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Zig
        run: |
          wget https://ziglang.org/download/$ZIG_VERSION/zig-linux-x86_64-$ZIG_VERSION.tar.xz
          tar -xf zig-linux-x86_64-$ZIG_VERSION.tar.xz
          mv zig-linux-x86_64-$ZIG_VERSION ~/zig
          echo "$HOME/zig" >> $GITHUB_PATH

      - name: Check Zig version
        run: zig version

      - name: Create bin/ directory
        run: mkdir bin

      - name: Build Windows X86_64
        run: |
          zig cc writeLicense.c main.c -target x86_64-windows-gnu -O2 -o bin/windows_x86_64.exe
          rm -rf bin/windows_x86_64.pdb

      - name: Build Windows ARM64
        run: |
          zig cc writeLicense.c main.c -target aarch64-windows-gnu -O2 -o bin/windows_arm64.exe
          rm -rf bin/windows_arm64.pdb

      - name: Build MacOS ARM64
        run: zig cc writeLicense.c main.c -target aarch64-macos -O2 -o bin/macos_arm64

      - name: Build MacOS X86_64
        run: zig cc writeLicense.c main.c -target x86_64-macos -O2 -o bin/macos_x86_64

      - name: Build Linux ARM64
        run: zig cc writeLicense.c main.c -target aarch64-linux-gnu -O2 -o bin/linux_arm64

      - name: Build Linux X86_64
        run: zig cc writeLicense.c main.c -target x86_64-linux-gnu -O2 -o bin/linux_x86_64
